// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://njcwpdgrdcxlaglvdxkx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5qY3dwZGdyZGN4bGFnbHZkeGt4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4NTUxNjIsImV4cCI6MjA2NzQzMTE2Mn0.zdBBVL3F7FIgweSvcpsupyOvldeyvLRvG_6bdlBxATE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});